services:
  mysql:
    image: mysql
    ports:
      - "3000:3306"
    networks:
      - my-network
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - app-mysql-data:/var/lib/mysql
    environment: # Những thông tin môi trường này là dùng cho cái image mysql:8.0 khởi tạo db
      MYSQL_DATABASE: keycloak
      MYSQL_USER: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: keycloak
    ports:
      - "8082:8080"
    networks:
      - my-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: 12345
      KC_DB_PASSWORD: 12345

    volumes:
      - ./my-realm.json:/opt/keycloak/data/import/realm.json

    command:
      - "start-dev"
      - "--import-realm"
    links:
      - mysql
    depends_on:
      - mysql

  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
    networks:
      - my-network


  app:
    depends_on:
      - mysql
    #    restart: on-failure
    image: zigkan/hotel_management_app:docker_ok_1.0
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
            "spring.jpa.show-sql" : "true",
            "spring.flyway.baseline-on-migrate" : "true",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "springdoc.api-docs.path" : "/api-docs",
            "springdoc.swagger-ui.path" : "/swagger-ui.html",
            "springdoc.swagger-ui.operationsSorter" : "method",
            "redis.host" : "localhost",
            "redis.port" : "6379",
            "keycloak.auth-server-url" : "http://keycloak:8080",
            "keycloak.realm" : "hotel-management-realm",
            "keycloak.resource" : "SpringBootKeycloak",
            "keycloak.credentials.secret" : "SpringBootKeycloakSecret",
            "keycloak.credentials.username" : "admin",
            "keycloak.credentials.password" : "admin",
            "spring.security.oauth2.resource-serve.jwt.issuer-uri" : "http://keycloak:8080/realms/hotel-management-realm",
            "spring.security.oauth2.resource-serve.jwt.jwk-set-uri" : "http://keycloak:8080/realms/hotel-management-realm/protocol/openid-connect/certs",
            "jwt.auth.converter.resourceId" : "SpringBootKeycloak",
            "jwt.auth.converter.principalAttribute" : "preferred_username",
            "logging.level.org.springframework.security" : "DEBUG"
          }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - my-network

volumes:
  app-mysql-data:

networks:
    my-network:
      driver: bridge